# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "osho"
  config.vm.hostname = "osho"
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  #config.vm.network "private_network", ip: "dhcp"



  # The first argument is the path on the host to the actual folder. 
  # The second argument is the path on the guest to mount the folder.
  config.vm.synced_folder "./html", "/var/www/html"

  

  config.vm.provider "virtualbox" do |vb|
    vb.name = "osho"
    vb.gui = false
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
  SHELL
  
  
  config.vm.provision "shell", run: "always", inline: <<-SHELL
  echo "Hello from the Vagrantfile"
  SHELL

  
end
